name: Validate

on:
  push:
    tags: ["v*"]

jobs:
  validate:
    name: Validate ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate
        uses: ./
        with:
          registry: docker.pkg.github.com
          namespace: ${{ github.repository }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          context: e2e
          dockerfile: e2e/Dockerfile
          image: example
          tag: latest
          target: runtime
